### ISSUE TITLE
[REQUEST] TODO

### ISSUE THREAD

**Issue by megastary** [houby-studio/small-business-fridge#45]
- [x] Add new product page - for admins
- [x] Add customize product page - for admins
- [ ] Add modify keypadID page - for supplier
- [ ] Add delivieries overview - for supplier (stock page rework?)
- [ ] Add send newsletter for suppliers?
- [x] Add/fix tooltip in invoice page
- [x] Add automatic reminder for users who did not pay invoice in week?
- [ ] AAD login handle name/email change?
- [x] Remove changelog / show only recent important change.
- [ ] Let supplier resend invoices
- [x] Let user display payment info / resend e-mail from e-shop
- [x] Change stock view for kiosk page as well
- [ ] Let admin change users permissions
- [ ] Let admin disable account - to be anonymized and excluded from e-mails and reports
- [x] Make e-mail buttons context aware
- [ ] Add more themes
- [ ] Add AI generation for product description

**Comment by megastary** [comment]
Change stock view for kiosk page as well
